site_name: 'Reading NOTES'
site_url: 'https://dengyouf.github.io/blog/'
site_author: "deng you"

repo_name: 'dengyouf/blog'
repo_url: 'https://github.com/dengyouf/blog'

theme:
  name: readthedocs
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

nav:
  - ANSIBLE:
      - Get started with Ansible: 'ansible/index.md'
      - Installation and Setup: 'ansible/02-install.md'
      - Playbooks Beginning: '03-playbooks.md'
  - DevOps:
      - 基于Jenkins和Argocd实现CI/CD:
          - Jenkins 安装: 'devops/jenkins.md'
